## Site Meta ##
# The title of the website.
title: "Wesley Scafe's Portfolio Site"
# The description of the website
description: "Wesley Scafe's Porfolio for Drafting, Design, Art, and 3D Modeling"
# Keywords/tags for you site.
keywords: "portfolio, drafting, design, art, 3D, photography, no-ai"
# Your copyright message.
copyright: "Copyright &copy; 2025 - Wesley Scafe"

## Site Configurations ##
# 1st heading of the site.
header: <img src=//images/"WesleyScafeLogo.png" alt="Wesley Scafe">
# 2nd heading/sub heading of the website.
subheader: "Drafting & Design"
# A description/bio of the website.
bio: "Projects including residential new builds, full home renovations, and technical drafting."
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: "wesley.scafe"
  # GitHub username.
  github_username: ""
  # Your email address.
  email: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "right center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true
